/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xu_jnicppdemo_MainActivity */

#ifndef _Included_com_xu_jnicppdemo_MainActivity
#define _Included_com_xu_jnicppdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xu_jnicppdemo_MainActivity
 * Method:    helloFromCPP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xu_jnicppdemo_MainActivity_helloFromCPP
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
